config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root 'items#index'
  resources :items, only: [:new, :create, :index, :show, :edit, :update,:destroy] do
    collection do
      get 'search_children'
      get 'search_grand_children'
      get 'credit'
      get 'user_edit'
      get 'signup_registration'
      get 'users_items_show/:id', to: 'items#users_items_show', as: :items_show
      post 'pay/:id' => 'items#pay'
      get 'buy/:id' => 'items#buy'
    end
  end
  resources :users, only: [:index, :show, :new, :edit] do
    collection do
      get 'profile'
      get 'logout'
      get 'credit'
      get 'identification'
      get 'mypage_ship'
      get 'sold'
    end
  end
  resources :payments do
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'complete' # 登録完了後のページ
    end
  end
end

app/views/module/_buy_image_box.html.haml
.items-box-content_main
  .items-box-content.clearfix
    .items-box-content_tag
      .items-box-content_tag_photo
        = image_tag "m49030494893_1.jpg", size: "220x220", alt: "test"
      .items-box-body
        .items-box-body_text_box
          %h3.items-box-name.font-2
            emmu.12 チーク ピンク系
          .items-box-num
            .items-box-price.font-5
              ¥450
            .items-box-price.font-2
              ♡3

    .items-box-content_tag
      .items-box-content_tag_photo
        = image_tag "m49030494893_1.jpg", size: "220x220", alt: "test"
      .items-box-body
        .items-box-body_text_box
          %h3.items-box-name.font-2
            emmu.12 チーク ピンク系
          .items-box-num
            .items-box-price.font-5
              ¥450
            .items-box-price.font-2
              ♡3

    .items-box-content_tag
      .items-box-content_tag_photo
        = image_tag "m49030494893_1.jpg", size: "220x220", alt: "test"
      .items-box-body
        .items-box-body_text_box
          %h3.items-box-name.font-2
            emmu.12 チーク ピンク系
          .items-box-num
            .items-box-price.font-5
              ¥450
            .items-box-price.font-2
              ♡3

app/views/module/_footer.html.haml
.footer
  = render 'module/footer_banner'
  .footer__link
    .footer__link-container.clearfix
      .footer-cell
        %h2.footer-head メルカリについて
        %ul
          %li
            = link_to '会社概要（運営会社）', '#'
          %li
            = link_to '採用情報', '#'
          %li
            = link_to 'プレスリリース','#'
          %li
            = link_to '公式ブログ','#'
          %li
            = link_to 'メルカリロゴ利用ガイドライン', '#'
          .footer-social-link
            = link_to("https://twitter.com/mercari_jp", target: "_blank") do
              %i.fa.fa-twitter
          .footer-social-link
            = link_to("https://www.facebook.com/mercarijp", target: "_blank") do
              %i.fa.fa-facebook-square
      .footer-cell
        %h2.footer-head ヘルプ＆ガイド
        %ul
          %li
            = link_to 'メルカリガイド', '#'
          %li
            = link_to 'らくらくメルカリ便', '#'
          %li
            = link_to 'ゆうゆうメルカリ便', '#'
          %li
            = link_to '大型メルカリ便', '#'
          %li
            = link_to '車体取引ガイド', '#'
          %li
            = link_to'メルカリあんしん・あんぜん宣言！', '#', target: :_blank
          %li
            = link_to '偽ブランド品撲滅への取り組み', '#'
          %li
            = link_to 'メルカリボックス', '#'
      .full-width
        %h2.footer-head プライバシーと利用規約
        .inner-footer-cell
          %ul
            %li
              =link_to 'プライバシーポリシー', '#'
            %li
              = link_to 'メルカリ利用規約', '#'
            %li
              = link_to 'あんしんスマホサポート制度に関する利用特約', '#'
            %li
              = link_to 'コンプライアンスポリシー','#'
        .inner-footer-cell
          %ul
            %li
              = link_to '個人データの安全管理に係る基本方針', '#'
            %li
              = link_to '特定商取引に関する表記', '#'
            %li
              = link_to '資金決済法に基づく表示', '#'
            %li
              = link_to '法令順守と犯罪抑止のために', '#'
      .footer-cell.footer-nav-lang
        %h2.footer-head 国
        %ul
          %li
            =link_to '日本', '#', class: "active"
          %li
            =link_to 'United States', '#'
    .footer__bottom
      = link_to image_tag("logo-white.svg"),("/items"), class: "footer-logo", size: "124x33", alt:"mercari"
      %span
        %small.footer-copyright © 2019 Mercari

app/views/module/_footer_banner.html.haml
.footer__banner{:style => "background-image:url(#{asset_path "download_app_bg.jpg"})"}
  .footer__banner-contents
    .footer__banner-contents--left
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner-icon.clearfix
        = image_tag "mercari_icon.png", size: "68x68", alt: "", class: "mercari_icon"
        = link_to image_tag("app-store.svg"),("https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8"), target: :_blank,class: 'store-icon'
        = link_to image_tag("google-play.svg"),("https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja"), target: :_blank,class: 'store-icon'
    %figure.footer__banner-contents--right
      = image_tag "download_content_pc.png", size: "300x260", alt: ""

app/views/module/_header.html.haml
.header
  .header__container
    .header__container__top
      %h1
        = link_to("/") do
          = image_tag "logo.svg", size: "134x36", alt: "mercari",class: "logo"
      .header__form
        = form_with(model: @items, local: true) do |f|
          = f.text_field :keyword, placeholder: "何かお探しですか？", type: "search", value: "", class: "header__input-default"
          %i.fa.fa-search.icon-search

    .header__container__bottom.clearfix
      .container__bottom-left
        %ul.header-nav
          %li
            %h2
              = link_to('#', class:'search-method') do
                %i.fa.fa-list-ul
                %span カテゴリーから探す
          %li
            %h2
              = link_to('#', class:'search-method') do
                %i.fa.fa-tag.icon
                %span ブランドから探す
      .container__bottom-right
        %ul.header-user-nav
          - if user_signed_in?
            %li
              = link_to('#', class: 'link') do
                %i.icon.fa.fa-heart-o
                %span いいね!一覧
            %li
              = link_to('#', class: 'link') do
                %i.icon.fa.fa-bell-o
                  .nav-count 5
                %span お知らせ
              %ul
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "mercari_profile.png", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 3日後、P999還元お得チケットの有効期限が切れます！タップして詳細を確認しましょう。
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "mercari_profile.png", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 【あと2日】参加ボタンを押すだけでポイントがもらえる！総額1億円相当還元！詳しくはこちら
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "mercari_profile.png", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 事務局から個別メッセージ「ログイン通知」
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "mercari_profile.png", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 《ご登録記念》¥1,000の商品を「実質1円」でご購入いただけます！
                      %i.fa.fa-chevron-right
                %li
                  = link_to user_path(current_user.id),class: "sublink" do
                    .sublink-content-logo
                      =image_tag "mercari_profile.png", size: "40x40", alt: "mercari"
                    .sublink-content-text
                      %span 【スマホを売ろう！】メルカリなら下取りよりも高く売れる♪いますぐ相場チェック！
                      %i.fa.fa-chevron-right
            %li
              = link_to('#', class: 'link') do
                %i.icon.fa.fa-check
                %span やることリスト
              %ul
                %li
                  = link_to (''),class: "sublink-todo" do
                    .sublink-content-todo
                      .sublink-content-todo-logo
                        = image_tag "logo-gray-icon.svg" ,size: "80x80"
                      .sublink-content-todo-text
                        %span 現在、やることリストはありません
            %li.list-mypage
              = link_to user_path(current_user.id) do
                = image_tag current_user.image ,size: "32x32", alt: "", class: "member_photo"
                %span マイページ
              %ul
                .sublink-mypage
                  %li
                    = image_tag "user-bg.jpg", size: "350x90",class: 'sublink-maypage-img'
                  %li
                    = image_tag current_user.image ,size: "75x75", alt: "", class: "sublink-maypagemember_photo"
                  %li
                    = link_to user_path(current_user.id),class: "sublink-maypage-link" do
                      ユーザー名：#{current_user.nick_name}
          - else
            .new-registration-btn
              = link_to '新規会員登録', new_user_path
            .log-in-btn
              = link_to 'ログイン', new_user_session_path

app/views/module/_mypage-sidebar.html.haml
.maypage__box__side
  %nav.maypage__box__side__sidebar
    %ul.maypage__box__side__sidebar__list
      %li
        = link_to(user_path(current_user.id), class: 'maypage__box__side__sidebar__list__item') do
          マイページ
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          お知らせ
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          やることリスト
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          いいね！一覧
          %i.fa.fa-chevron-right
      %li
        = link_to("/items/new", class: 'maypage__box__side__sidebar__list__item') do
          出品する
          %i.fa.fa-chevron-right
      %li
        = link_to("/users/mypage_ship", class: 'maypage__box__side__sidebar__list__item') do
          出品した商品 - 出品中
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          出品した商品 - 取引中
          %i.fa.fa-chevron-right
      %li
        = link_to("/users/sold", class: 'maypage__box__side__sidebar__list__item') do
          出品した商品 - 売却済み
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          購入した商品 - 取引中
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          購入した商品 - 過去の取引
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          ニュース一覧
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          評価一覧
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          ガイド
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          お問い合わせ
          %i.fa.fa-chevron-right
    %h3.maypage__box__side__head
      メルペイ
    %ul.maypage__box__side__sidebar__list
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          売上・振込申請
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          ポイント
          %i.fa.fa-chevron-right
    %h3.maypage__box__side__head
      設定
    %ul.maypage__box__side__sidebar__list
      %li
        = link_to("/users/profile", class: 'maypage__box__side__sidebar__list__item') do
          プロフィール
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          発送元・お届け先住所変更
          %i.fa.fa-chevron-right
      %li
        = link_to("/items/credit", class: 'maypage__box__side__sidebar__list__item') do
          支払い方法
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          メール/パスワード
          %i.fa.fa-chevron-right
      %li
        = link_to("/users/identification", class: 'maypage__box__side__sidebar__list__item') do
          本人情報
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          電話番号
          %i.fa.fa-chevron-right
      %li
        = link_to("#", class: 'maypage__box__side__sidebar__list__item') do
          電話番号の確認
          %i.fa.fa-chevron-right
      %li
        = link_to("/users/logout", class: 'maypage__box__side__sidebar__list__item') do
          ログアウト
          %i.fa.fa-chevron-right

app/views/module/_mypage_ship.html.haml
= link_to items_show_items_path(item), class: "mypage-item-link" do
  - if item.images.attached?
    - item.images.first(1).each do |image|
      = image_tag image ,size: "64x55" ,class: "is-higher-width"
      .mypage-item-body
        .mypage-item-text
          = item.name
          .mypage-item-status.awaiting
            出品中

app/views/module/_sell-btn.html.haml
%a.sell-btn{href: "/items/new"}
  %div 出品
  %i.fa.fa-camera

app/views/module/_sell_item.html.haml
.single-main
= form_with(model: @item, url: items_path, local: true) do |f|
  %section.shipping-single-container
    .sell_container
      .sell-container-inner
        %h2.l-single-head
          商品の情報を入力
        .sell-form
          .sell-upload-box
            %h3.sell-upload-head
              出品画像
              %span.form-require
                必須
            %p
              最大10枚までアップロードできます
            .sell-dropbox-container.clearfix
              .sell-upload-items-container
                .sell-upload-items
                  %ul
            .sell-upload-drop-box
              %label
                = f.file_field :images, multiple: true, class: "image_file_select"
                %pre.visible-pc
                  ドラッグアンドドロップ
                  またはクリックしてファイルをアップロード
            %pseudo:after
            %pseudo:after
          .sell-content
            .form-group
              %label
                商品名
                %span.form-require
                  必須
              .item_subumit_form
                = f.text_field :name, placeholder: "商品名（必須 40文字まで)", value: "", class: 'input-default_shipping'
            .form-group
              %label
                商品の説明
                %span.form-require
                  必須
              = f.text_area :description, placeholder: "商品の説明（必須 1,000文字以内）", value: "", class: 'textarea-default'

          .sell-content_secoud
            %h3.sell-sub-head
              商品の詳細
            .sell-form-box
              .form-group_first
                %label
                  カテゴリー
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :category_id, Categoryhash.all, :id, :name

              .form-group
                %label
                  サイズ
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :size_id, Size.all, :id, :name

              .form-group
                %label
                  商品の状態
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :condition_id, Condition.all, :id, :name

          .sell-content_secoud
            %h3.sell-sub-head
              配送について
              %i.fa.fa-question-circle
            .sell-form-box
              .form-group_first
                %label
                  配送料金の負担
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :shipfee_id, Shipfee.all, :id, :name

              .form-group
                %label
                  配送の方法
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :shipmethod_id, Shipmethod.all, :id, :name

              .form-group
                %label
                  発送元の地域
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :prefecture_id, Prefecture.all, :id, :name

              .form-group
                %label
                  発送までの日数
                %span.form-require 必須
                .select-wrap-box
                  %i.fa.fa-angle-down
                    %pseudo:before
                  .select-wrap-box_prefecture
                    .select-wrap
                      = f.collection_select :shipdate_id, Shipdate.all, :id, :name

          .sell-content_secoud_under
            %h3.sell-sub-head_under
              販売価格(300〜9,999,999)
              %i.fa.fa-question-circle
            %a.form-question{:href => "/jp/help_center/article/64/", :target => "_blank"}
            .sell-form-box_under
              %ul.sell-price
                %li.form-group_under_first
                  .form-group_price_box
                    %label.l-left
                      価格
                      %span.form-require
                        必須
                    .l-right.sell-price-input
                      ¥
                      .input-default_box
                        = f.text_field :price, placeholder: "例）300", value: "", class: 'input-default_price',  type:"tel"

            .sell-form-box_under_second
              %p
                販売手数料 (10%)
            .sell-form-box_under_third
              %p
                販売利益
    .btn-container
      .btn-container_text
        %p
          = link_to "禁止されている出品", "/jp/help_center/getting_started/prohibited_items/" ,target: "_blank"
          = link_to "行為", "/jp/help_center/getting_started/prohibited_conduct/" ,target: "_blank"
          を必ずご確認ください。
        %p
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to "偽ブランドの販売", "/jp/help_center/getting_started/counterfeit_goods/" ,target: "_blank"
          は犯罪であり処罰される可能性があります。
        %p
          また、出品をもちまして
          = link_to "加盟店規約", "/jp/seller_terms/"
          に同意したことになります。
      = f.submit '出品する', class: 'btn-default btn-red' do
        出品する
      %a.btn-default.btn-gray
        もどる

app/views/module/_sold.html.haml
= link_to items_show_items_path(item), class: "mypage-item-link" do
  - if item.images.attached?
    - item.images.first(1).each do |image|
      = image_tag image ,size: "64x55" ,class: "is-higher-width"
      .mypage-item-body
        .mypage-item-text
          = item.name
          .mypage-item-status_box
            売却済

app/views/module/_subfooter.html.haml
.sub-footer
  .sub-footer-in
    .navi
      %ul
        %li
          = link_to "プライバシーポリシー",("#")
        %li
          = link_to "メルカリ利用規約",("#")
        %li
          = link_to "特定商取引に関する表記",("#")
    .footer-logo
      = link_to image_tag("footer-logo.svg"),("/items")
    %p © 2019 Mercari

app/views/module/_subheader.html.haml
.sub-header
  %h1
    = link_to image_tag("logo.svg"),("/items")