config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root 'items#index'
  resources :items, only: [:new, :create, :index, :show, :edit, :update,:destroy] do
    collection do
      get 'search_children'
      get 'search_grand_children'
      get 'credit'
      get 'user_edit'
      get 'signup_registration'
      get 'users_items_show/:id', to: 'items#users_items_show', as: :items_show
      post 'pay/:id' => 'items#pay'
      get 'buy/:id' => 'items#buy'
    end
  end
  resources :users, only: [:index, :show, :new, :edit] do
    collection do
      get 'profile'
      get 'logout'
      get 'credit'
      get 'identification'
      get 'mypage_ship'
      get 'sold'
    end
  end
  resources :payments do
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'complete' # 登録完了後のページ
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def step1
    @user = User.new # 新規インスタンス作成
  end

  def step2
    # step1で入力された値をsessionに保存
    session[:nick_name] = user_params[:nick_name]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:birth_year] = user_params[:birth_year]
    session[:birth_month] = user_params[:birth_month]
    session[:birth_day] = user_params[:birth_day]
    session[:family_name] = user_params[:family_name]
    session[:family_kana] = user_params[:family_kana]
    session[:first_name] = user_params[:first_name]
    session[:first_kana] = user_params[:first_kana]

    @user = User.new # 新規インスタンス作成
  end

  def step3
    # step2で入力された値をsessionに保存
    session[:phone_number] = user_params[:phone_number]
    @user = User.new # 新規インスタンス作成
  end

  def step4
    # step3で入力された値をsessionに保存
    session[:zip] = user_params[:zip]
    session[:prefecture_id] = user_params[:prefecture_id]
    session[:city] = user_params[:city]
    session[:block] = user_params[:block]
    session[:building] = user_params[:building]
    @user = User.new # 新規インスタンス作成
  end


  def complete
    sign_in User.find(session[:id]) unless user_signed_in?
    render :complete
  end

  def create
    @user = User.new(
      nick_name: session[:nick_name], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_kana: session[:family_kana],
      first_kana: session[:first_kana],
      phone_number: session[:phone_number],
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      zip: session[:zip],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      block: session[:block],
      building: session[:building],
      payment_id: session[:payment_id],
    )
    if @user.save
      session[:id] = @user.id
      redirect_to complete_signup_index_path
    else
      render '/signup/step1'
    end
  end


  private
    # 許可するキーを設定します
    def user_params
      params.fetch(:user,{}).permit(
        :email,
        :password,
        :password_confirmation,
        :nick_name,
        :family_name,
        :family_kana,
        :first_name,
        :first_kana,
        :phone_number,
        :birth_year,
        :birth_month,
        :birth_day,
        :zip,
        :prefecture_id,
        :city,
        :block,
        :building,
        :payment_id,
    )
    end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/complete.html.haml
.header-complete
  = render 'devise/shared/user-sign_up-header'

.user-complete
  .user-complete__contents
    .user-complete__contents__top
      %h2 会員登録完了
    .user-complete__contents__main
      %div ありがとうございます。
      %div 会員登録が完了しました。
    .user-complete__contents__bottom
      = link_to 'メルカリをはじめる', root_path, class: 'complete-btn'

= render 'module/footer_banner'
= render 'module/subfooter'

app/views/signup/step1.html.haml
%header
  .signup-headerwrapper
    = render 'devise/shared/user-sign_up-header.html.haml'
.signup-registration
  .signup-registration__main
    %section.signup-registration__main__container
      %h2.signup-registration__main__container__head
        会員情報入力
      .signup-registration__main__container__form
        = form_with(model: @user, url: step2_signup_index_path,method: :get, local: true) do |f|
          = render 'layouts/error_messages', model: f.object
          .signup-registration__main__container__form__box
            .signup-registration-from-group-head
              = f.label :nick_name, 'ニックネーム', class: 'signup-registration-label'
              %span.signup-registration-form-require
                必須
              = f.text_field :nick_name, placeholder: "例) メルカリ太郎", class: 'signup-registration-from-input'
            .signup-registration-from-group
              = f.label :email, 'メールアドレス', class: 'signup-registration-label email'
              %span.signup-registration-form-require
                必須
              = f.text_field :email, placeholder: "PC・携帯どちらでも可", class:'signup-registration-from-input'
            - if @user.email.blank?
              .signup-registration-from-group
                = f.label :password, 'パスワード', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
                = f.password_field :password, placeholder: "7文字以上", autocomplete: "new-password", class: 'signup-registration-from-input'
              .signup-registration-from-group
                = f.label :password_confirmation, 'パスワード(確認)', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
                = f.password_field :password_confirmation, placeholder: "7文字以上", autocomplete: "new-password", class: 'signup-registration-from-input'
            - else
              .signup-registration-from-group.reg-pass{ style: "display:none" }
                = f.label :password, 'パスワード', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
                = f.password_field :password, placeholder: "7文字以上", autocomplete: "new-password", class: 'signup-registration-from-input',value: "#{@user.password}"
              .signup-registration-from-group.reg-pass-conf{ style: "display:none" }
                = f.label :password_confirmation, 'パスワード(確認)', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
                = f.password_field :password_confirmation, placeholder: "7文字以上", autocomplete: "new-password", class: 'signup-registration-from-input',value: "#{@user.password_confirmation}"
            .signup-registration-from-group
              %h3.signup-registration-sub-head
                本人確認
              %p.signup-registration-text
                安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .signup-registration-from-group
              .div
                = f.label :family_name, 'お名前(全角)', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
              = f.text_field :family_name, placeholder: "例) 山田", class: 'signup-registration-from-input half1'
              = f.text_field :first_name, placeholder: "例) 彩", class: 'signup-registration-from-input half2'
            .signup-registration-from-group
              .div
                = f.label :family_kana, 'お名前(カナ)', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
              = f.text_field :family_kana, placeholder: "例) ヤマダ", class: 'signup-registration-from-input half1'
              = f.text_field :first_kana, placeholder: "例) アヤ", class: 'signup-registration-from-input half2'
            .signup-registration-from-group
              .div
                = f.label :birth_year_id, '生年月日', class: 'signup-registration-label'
                %span.signup-registration-form-require
                  必須
                .birthday-select-box
                  .birthday-select-box-block
                    %i.fa.fa-chevron-down
                    = f.collection_select(:birth_year, Birth_year.all, :id, :name, {selected: 0}, {class: "signup-registration-from-input select"})
                  %span
                    年
                  .birthday-select-box-block
                    %i.fa.fa-chevron-down
                    = f.collection_select(:birth_month, Birth_month.all, :id, :name, {selected: 0}, {class: "signup-registration-from-input select"})
                  %span
                    月
                  .birthday-select-box-block
                    %i.fa.fa-chevron-down
                    = f.collection_select(:birth_day, Birth_day.all, :id, :name, {selected: 0}, {class: "signup-registration-from-input select"})
                  %span
                    日
            %p.form-info-box
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
            .signup-registration__main__container__form__box
              .signup-registration-from-group
                = image_tag 'robbot.png', size: '304x74'
              .signup-registration-from-group
                %p.signup-registration-text-lower
                  「次へ進む」のボタンを押すことにより、
                  = link_to("#", class: 'right-text-link') do
                    利用規約
                  に同意したものとみなします
              .signup-registration-from-group
                = f.submit "次へ進む",class: "signup-registration-btn"
              .signup-registration-from-group-last
                = link_to("#", class: 'right-text-link') do
                  本人情報の登録について
                  %i.fa.fa-chevron-right"
%footer
  = render 'module/subfooter'

app/views/signup/step2.html.haml
.header_phone_authentification
  = render 'devise/shared/user-sign_up-header'

%main.single-main
  .l-single-container
    %h2.l-chapter-head.registration 電話番号の確認
    = form_with(model: @user ,url: step3_signup_index_path, method: :get, local: true, class: "l-single-inner registration-form") do |f|
      .l-single-content
        .form-group2
          = f.label :phone_number, '携帯電話の番号'
          = f.text_field :phone_number, placeholder: "携帯電話の番号を入力", type: "tel", value: "", class: "input-default"
        %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        = f.submit 'SMSを送信する', class: "btn-default btn-red"
        %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        .form-group2.text-right
          = link_to('https://www.mercari.com/jp/help_center/article/244/', target: "_blank") do
            %p 電話番号の承認が必要な理由
            %i.icon-arrow-right

= render 'module/subfooter'

app/views/signup/step3.html.haml
.header-address_input
  = render 'devise/shared/user-sign_up-header'

%main.single-main
  .l-single-container
    %h2.l-chapter-head.registration 住所入力
    = form_with(model: @user ,url: step4_signup_index_path,method: :get, local: true, class: "l-single-inner registration-form") do |f|
      .l-single-content
        .form-group2
          .form-block
            = f.label :family_name, "お名前"
            %span.arbitrary-mark-red
              必須
            = f.text_field :family_name, placeholder: "例)山田", type: "text", value: "#{session[:family_name]}", class: "input-identification-form"
            = f.text_field :first_name, placeholder: "例)彩", type: "text", value: "#{session[:first_name]}", class: "input-identification-form"
          .form-block
            %label
            = f.label :family_name, "お名前カナ"
            %span.arbitrary-mark-red
              必須
            = f.text_field :family_kana, placeholder: "例)ヤマダ", type: "text", value: "#{session[:family_kana]}", class: "input-identification-form"
            = f.text_field :first_kana, placeholder: "例)アヤ", type: "text", value: "#{session[:first_name]}", class: "input-identification-form"
          .form-block
            = f.label :zip_code, "郵便番号"
            %span.arbitrary-mark-red
              必須
            = f.text_field :zip, placeholder: "例)1234567", type: "text", value: "", class: "input-identification-form"
          .form-block
            = f.label :prefecture_id, "都道府県"
            %span.arbitrary-mark-red
              必須
            .select-box
              %i.fa.fa-chevron-down
              .select-box__prefecture
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name
          .form-block
            = f.label :city, "市区町村"
            %span.arbitrary-mark-red
              必須
            = f.text_field :city, placeholder: "例) 横浜市緑区", type: "text", value: "", class: "input-identification-form"
          .form-block
            = f.label :block, "番地"
            %span.arbitrary-mark-red
              必須
            = f.text_field :block, placeholder: "例) 青山1−1−1", type: "text", value: "", class: "input-identification-form"
          .form-block
            = f.label :building, "建物名"
            %span.arbitrary-mark-gray
              任意
            = f.text_field :building, placeholder: "例) 柳ビル103", type: "text", value: "", class: "input-identification-form"
          .form-block
            = f.label :phone_number, "電話"
            %span.arbitrary-mark-gray
              任意
            = f.text_field :phone_number, placeholder: "例) 09012345678", type: "text", value: "#{session[:phone_number]}", class: "input-identification-form"
            = f.submit "登録する", class: "input-identification-registration_btn"

= render 'module/subfooter'

app/views/signup/step4.html.haml
.credit_single_header
  = render 'devise/shared/user-sign_up-header'

.credit_single-main
  %section.l-single-container
    %h2.l-single-head.registration
      支払い方法
    .l-single-inner.registration-form
      = form_with(model: @user, url: signup_index_path, method: :post, local: true) do |f|
        %input{:name => "__csrf_value", :type => "hidden", :value => "#"}/
        .l-single-content
          .credit_form-group
            %label{:for => "payment_card_no"} カード番号
            %span.form-require 必須
            %input#payment_card_no.input-default{"data-input-type" => "card", :maxlength => "19", :placeholder => "半角数字のみ", :type => "text", :value => ""}/
            %ul#card-no-error-wrapper.has-error-text
            .signup-card-list
              = image_tag "card.png", alt: "test"
          .credit_form-group.signup-form-expire
            .credit_form-group_box1
              %label.payment_card_expire 有効期限
              %span.form-require 必須
              .select-wrap_box.half
                = f.collection_select(:birth_month_id, Birth_month.all, :id, :name,{selected: 0}, {class: "select-default"})
                %span 月
                = f.collection_select(:yearactive_id, Yearactive.all, :id, :name,{selected: 0}, {class: "select-default"})
                %span 年
            .credit_form-group_box1
              %label{:for => "payment_card_security_code"} セキュリティコード
              %span.form-require 必須
              %input#payment_card_security_code.input-default{:placeholder => "カード背面4桁もしくは3桁の番号", :type => "number", :value => ""}/
              .signup-seqcode
                .signup-seqcode-text
                  %span.form-question ?
                  カード裏面の番号とは?
            = f.submit "次へ進む", class: "btn-red btn-default", id: "submit-button"
= render 'module/subfooter'