config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root 'items#index'
  resources :items, only: [:new, :create, :index, :show, :edit, :update,:destroy] do
    collection do
      get 'search_children'
      get 'search_grand_children'
      get 'credit'
      get 'user_edit'
      get 'signup_registration'
      get 'users_items_show/:id', to: 'items#users_items_show', as: :items_show
      post 'pay/:id' => 'items#pay'
      get 'buy/:id' => 'items#buy'
    end
  end
  resources :users, only: [:index, :show, :new, :edit] do
    collection do
      get 'profile'
      get 'logout'
      get 'credit'
      get 'identification'
      get 'mypage_ship'
      get 'sold'
    end
  end
  resources :payments do
  end
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'complete' # 登録完了後のページ
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  require "payjp"
  before_action :set_card

  def index
    if @payment.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY
      customer = Payjp::Customer.retrieve(@payment.customer_id)
      @customer_card = customer.cards.retrieve(@payment.card_id)
    end
  end

  def new
  end

  def create
    Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY

    if params['payjp-token'].blank?
      redirect_to action: "new", alert: '登録に失敗しました'
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @payment = Payment.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @payment.save
        redirect_to controller: "items", action: "credit"
      else
        redirect_to new_payment_path, alert: '登録に失敗しました'
      end
    end
  end

  def destroy
    if @payment.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_SECRET_KEY
      customer = Payjp::Customer.retrieve(@payment.customer_id)
      customer.delete
      @payment.delete
      redirect_to new_payment_path, notice: '削除しました'
    end
  end

  private
  def set_card
    @payment = Payment.where(user_id: current_user.id).first if Payment.where(user_id: current_user.id).present?
  end
end

app/views/payments/index.html.haml
%header
  = render 'module/header.html.haml'
- breadcrumb :credit

.mypage
  %main.mypage__box
    .maypage-sidebar
      = render 'module/mypage-sidebar'
    .credit-box
      .credit-box-in
        .credit-box-in__top
          %h2 支払い方法
        .credit-box-in__main
          %section.credit-box-in__main__info
            .credit-info
              %h3 クレジットカード一覧
            .customer-card__box
              .customer-card__box__content
                %figure.form_space
                = image_tag "Visa_logo.svg", size: "50x30"
              .customer-card__box__content--number.form_space
                %h3
                  = "************" + @customer_card.last4
              .customer-card__box__content--expired.form_space
                - exp_month = "0#{@customer_card.exp_month.to_s}"
                - exp_year = @customer_card.exp_year.to_s.slice(2,3)
                %h3
                  = exp_month + " / " + exp_year
              = link_to payment_path(@payment.id), method: :delete, class:"customer-card__content--btn" do
                %button.card_destroy_btn
                  削除する
          .pay_link
            = link_to("#", class: 'right-text-link pay-text_link') do
              支払い方法について
              %i.fa.fa-chevron-right

= render 'module/footer'
= render 'module/sell-btn'

app/views/payments/new.html.haml
%header
  = render 'module/header.html.haml'
- breadcrumb :payments_new

.mypage
  %main.mypage__box
    .maypage-sidebar
      = render 'module/mypage-sidebar'
    .mypage__box__content
      .mypage__box__content__payments_new
        %h2.mypage__box__content__payments_new-head
          クレジットカード情報入力
        .add-l-single-inner.registration-form
          = form_with url: payments_path, method: :post, html: { name: "inputForm" } do |f|
            .l-single-content
              .add_credit_form-group
                = f.label :カード番号, class: 'label'
                %span.form-require 必須
                = f.text_field :card_number, type: 'text', placeholder: '半角数字のみ', maxlength: "16", class: 'input-default'
                %ul#card-no-error-wrapper.has-error-text
                .signup-card-list
                  = image_tag "card.png", alt: "test"
              .add_credit_form-group.signup-form-expire
                .add_credit_form-group_box1
                  = f.label :有効期限, class: 'payment_card_expire'
                  %span.form-require 必須
                  .select-wrap_box.half#add-card
                    = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: "select-default"
                    %span 月
                    = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: "select-default"
                    %span 年
                .add_credit_form-group_box1
                  = f.label :セキュリティコード, class: 'label'
                  %span.form-require 必須
                  = f.text_field :cvc, type: 'text', class: 'input-default', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
                  .signup-seqcode
                    .signup-seqcode-text
                      %span.form-question ?
                      カード裏面の番号とは?
                .content-bottom#card_token
                  = f.submit '追加する', class: 'btn-red btn-default', id: 'token_submit'
= render 'module/footer'
= render 'module/sell-btn'

:javascript
  document.addEventListener(
    "DOMContentLoaded", e => {
      if (document.getElementById("token_submit") != null) {
        Payjp.setPublicKey("pk_test_2b103472b5d99a9500ccd485");
        let btn = document.getElementById("token_submit");
        btn.addEventListener("click", e => {
          e.preventDefault();
          let card = {
            number: document.getElementById("card_number").value,
            cvc: document.getElementById("cvc").value,
            exp_month: document.getElementById("exp_month").value,
            exp_year: document.getElementById("exp_year").value
          };
          Payjp.createToken(card, (status, response) => {
            if (status === 200) {
              $("#card_number").removeAttr("name");
              $("#cvc").removeAttr("name");
              $("#exp_month").removeAttr("name");
              $("#exp_year").removeAttr("name");
              $("#card_token").append(
                $('<input type="hidden" name="payjp-token">').val(response.id)
              );
              document.inputForm.submit();
              alert("登録が完了しました");
            } else {
              alert("カード情報が正しくありません。");
            }
          });
        });
      }
    },
    false
  );